version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 8888:5432
    environment:
      POSTGRES_USER: postgres,
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: contactdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pg@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres 

volumes:
  postgres-data:
    driver: local
  